# Generated by Django 5.1.4 on 2025-04-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_seller_requested",
            field=models.BooleanField(default=False),
        ),
    ]
