# Generated by Django 5.0 on 2025-05-24 04:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_deduplicate_chatrooms'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': 'timestamp', 'ordering': ['timestamp']},
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['product', 'customer', 'is_active'], name='chat_chatro_product_d4af62_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'sender', 'is_read'], name='chat_messag_room_id_05d7d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='chatroom',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('product', 'customer', 'is_active'), name='unique_user_product_chat'),
        ),
    ]
