# Generated by Django 5.0 on 2025-03-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="delivered_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
