# Generated by Django 5.1.4 on 2025-03-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                default="015751B773", editable=False, max_length=20, unique=True
            ),
        ),
    ]
