# Generated by Django 5.1.4 on 2025-03-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_order_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                default="8F216A37D1", editable=False, max_length=20, unique=True
            ),
        ),
    ]
