# Generated by Django 5.0 on 2025-03-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                default="8700A2435E", editable=False, max_length=20, unique=True
            ),
        ),
    ]
