# Generated by Django 5.0 on 2025-03-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                default="E4DEDE6B55", editable=False, max_length=20, unique=True
            ),
        ),
    ]
