# Generated by Django 5.1.4 on 2025-03-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_orderitem_variant_alter_order_order_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(
                default="C3F4725970", editable=False, max_length=20, unique=True
            ),
        ),
    ]
