# Generated by Django 5.1.4 on 2025-03-23 16:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_alter_order_order_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Discount percentage (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Max number of uses, null for unlimited",
                        null=True,
                    ),
                ),
                (
                    "uses",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times used"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="orders.coupon",
            ),
        ),
    ]
