# Generated by Django 5.1.4 on 2025-03-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_coupon_order_discount_amount_order_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
