# Generated by Django 5.1.4 on 2025-04-30 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="default_variant",
            field=models.ForeignKey(
                blank=True,
                help_text="Default variant to display in product card and detail page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="featured_in",
                to="products.productvariant",
            ),
        ),
    ]
