# Generated by Django 5.0 on 2025-05-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_default_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='certificate_description',
            field=models.TextField(blank=True, help_text='Certificate description in rich text (HTML)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Upload a certificate file (PDF or Image)', null=True, upload_to='product_certificates/'),
        ),
    ]
